revamped environmental variables

diff --git a/src/bash/bashrc b/src/bash/bashrc
--- a/src/bash/bashrc
+++ b/src/bash/bashrc
@@ -54,6 +54,114 @@
     fi
 }
 
+{ # ENVIRONMENTAL VARIABLES
+    _isMac && export GLOBIGNORE=.DS_Store:.CFUserTextEncoding:.localized:.hushlogin
+    export CDPATH=.:~
+    export LSCOLORS=$'Dxfxcxdxbxegedabagacad';      # default =. 'exfxcxdxbxegedabagacad'
+    export HISTFILE=~/.bash_history
+    export HISTFILESIZE=100000
+    export HISTSIZE=100000
+    export HISTCONTROL='ignoreboth'
+    export MYSQL_HISTFILE=~/.mysql_history
+    export LESSHISTFILE=~/.less_history
+    export LESSHISTSIZE=10000
+    export EDITOR='vim'
+
+    { # SET PROMPT VARIABLE (PS1)
+
+        if ((EUID == 0)); then
+            # set root prompt
+            export PS1=$'\[\e[41;37;1m[\u]\W\[\e[00m\]-\[\e[36;1m\]\#\[\e[00m\]\$ '
+        else
+            export PS1=$'[\[\e[33;1m\]\W\[\e[00m\]] \e[36;1m\]\#\[\e[00m\] \$ '
+        fi
+    }
+
+    { # SET PROMPT_COMMAND
+    
+        unset -f ps1_command
+
+        function ps1_command() {
+            local -ir xit=$?;
+            if (( xit != 0 )); then
+                echo
+                _err "=> $(history 1 | sed 's:^[[:blank:]]*[0-9][0-9]*[[:blank:]]*\(.*$\):\1:')";
+                echo
+            fi
+            return ${xit}
+        }
+
+        if ! echo "${PROMPT_COMMAND}" | grep -q 'ps1_command'; then
+            PROMPT_COMMAND='ps1_command'"${PROMPT_COMMAND:+";${PROMPT_COMMAND}"}"
+        fi
+
+    }
+
+    { # LOCATION VARIABLES
+        if [[ -n "${_location_variables[*]}" ]]; then
+            # unset all location variables
+            for key in "${!_location_variables[@]}"; do
+                unset "${key}"
+            done
+        fi
+        unset _location_variables
+        
+        declare -A _location_variables; _location_variables=()
+        declare -A _location_variable_errors; _location_variable_errors=()
+
+        function validateAndSetLocationVariables() {
+            local NAME DIR;
+            NAME="${1:?}" DIR="${2:?}"
+            if [[ ! -d "${DIR}" ]]; then
+                _location_variable_errors["${NAME}"]="${DIR}"
+                (( DEBUG_LEVEL >= -1 )) && _err "unable to set variable. directory not found -- ${DIR}"
+                return 1
+            fi
+            if [[ -n "${!NAME}" ]]; then
+                _location_variable_errors["${NAME}"]="${DIR}"
+                (( DEBUG_LEVEL >= 0 )) && _err "name has already been set previously -- ${!NAME}"
+                return 2
+            fi
+            eval "${NAME}=\"${DIR}\""
+            if [[ -n "${!NAME}" && "${!NAME}" == "${DIR}" ]]; then
+                _location_variables["${NAME}"]="${DIR}"
+                (( DEBUG_LEVEL == 1 )) && _success "${NAME} => ${!NAME}"
+            fi
+        }
+
+        { # set location variables here
+            (( DEBUG_LEVEL >= 0 )) && printf '\n  [%s] => %s\n\n' 'clienv' 'setting location variables';
+            if _isMac; then
+                validateAndSetLocationVariables "clienv" ~/Desktop/clienv
+                validateAndSetLocationVariables "dev" ~/Developer
+                validateAndSetLocationVariables "repos" ~/Developer/repos
+                validateAndSetLocationVariables "desk" ~/Desktop
+                validateAndSetLocationVariables "docs" ~/Documentssssss
+                validateAndSetLocationVariables "dl" ~/Downloads
+                validateAndSetLocationVariables "sites" ~/Sites
+                validateAndSetLocationVariables "favs" ~/Library/Favorites/
+                validateAndSetLocationVariables "proj" ~/Projects
+                validateAndSetLocationVariables "var" /private/var
+                validateAndSetLocationVariables "etc" /private/etc
+                validateAndSetLocationVariables "uvar" /usr/local/var
+                validateAndSetLocationVariables "uetc" /usr/local/etc
+                validateAndSetLocationVariables "uetc2" /usr/local/etcc
+                validateAndSetLocationVariables "uetc" /usr/local/
+            fi
+        }
+
+	shopt -s cdable_vars
+
+        if (( ${#_location_variable_errors[@]} > 0 )); then
+            (( DEBUG_LEVEL >= 0 )) && _err "location variable assignment errors occurred (${#_location_variable_errors[@]})"
+        fi
+        
+        # clean up
+        unset -f validateAndSetLocationVariables
+        unset _location_variable_errors
+    }
+}
+
 { # USER ALIASES
 
     _isMac && alias ls='ls -Gtx' \
